# Stage 1: Build the Application
FROM maven:3.8.3-openjdk-17 AS build
# Set the working directory
WORKDIR /app
# Copy the project files into the build stage
COPY . . 
# Build the project, resulting in the JAR file in /target/
RUN mvn clean install -DskipTests

FROM openjdk:17-jre-slim
COPY --from=build /app/target/drive-fund-0.0.1-SNAPSHOT.jar savingsapp.jar
EXPOSE 8080
ENTRYPOINT [ "java","-jar","savingsapp.jar" ]

